remove dependency on TeX
vijayvarma392/gw_eccentricity pull request #183
Opened 2023-04-23 02:52 UTC by md-arif-shaikh

Existing plot settings were using `usetex=True` by default which requires `TeX` installation. This PR makes `usetex=False` by default and hence requires no `TeX` installation for things to work smoothly.

2023-04-23 09:33 UTC, vijayvarma392 requested changes
Can you also please look into why the CI is not running for this PR?

2023-04-23 09:33 UTC, vijayvarma392 commented on examples/gw_eccentricity_demo.ipynb
> +    "use_fancy_plotsettings(usetex=False)    # for better looking plots"
Remove the comment, because it sounds like usetex=False leads to better-looking plots.

2023-04-23 09:33 UTC, vijayvarma392 commented on examples/load_waveform_demo.ipynb
> +    "use_fancy_plotsettings(usetex=False) # use better defaults for plotting\n",
Same comment.

2023-04-24 13:05 UTC, md-arif-shaikh commented
I am closing this since the changes are moved to PR #184 from this fork to a  branch. PR from this fork was not starting the CI, PR from the branch does not have this issue.

2023-04-24 13:05 UTC, closed without merging